ember-cli/ember-try

- lib/utils/scenario-manager.js
Fixes https://github.com/kategengler/ember-try/issues/3
So I included the suggestion that @rwjblue had, as well as I'm preserving the resolutions. Now in your scenario files you can optionally specify a resolutions object, like this:
```javascript
module.exports = {
scenarios: [
{
name: 'ember-release',
dependencies: {
"ember": "components/ember#release"
},
resolutions: {
"ember": "release"
}
},
{
name: 'ember-beta',
dependencies: {
"ember": "components/ember#beta"
},
resolutions: {
"ember": "beta"
}
},
{
name: 'ember-canary',
dependencies: {
"ember": "components/ember#canary"
},
resolutions: {
"ember": "canary"
}
}
]
};
```
or if you are not using shims, you can specify something like this:
```javascript
module.exports = {
scenarios: [
{
name: 'ember-release',
dependencies: {
"ember": …
```
> fixes #3: remove actual version check and preserve resolutions

- lib/tasks/testall.js
- lib/tasks/try.js
- lib/utils/bower-helpers.js
- lib/utils/find-ember-path.js
- package.json
This PR removes the need for global `ember` and `bower` commands.
* `ember` is looked up via a normal `resolve` from the consuming projects directory.
* `bower` is resolved relative to `ember`'s path.  This ensures that we are using the embedded version of Bower from Ember CLI (instead of requiring global `bower`).
Fixes #11.
> Do not require global `bower` or `ember` commands.

- lib/commands/try.js
- lib/tasks/try.js
Allows:
```
ember try ember-canary test --server
```
Fixes #10.
> Allow all command arguments to be passed through.

- README.md
- lib/commands/testall.js
- lib/commands/try.js
- lib/tasks/testall.js
- lib/tasks/try.js
When running in a CI environment like travis the cleanup is just extra
time wasted.  —skip-cleanup will prevent the reset from running.
I only added this to the try command, if you want I’m happy to add it to testall as well, but I'm not sure if that has the same use case.
I did a thing with a fake promise in the try task that might be the wrong approach, but I'm not super familiar with writing commands and I wasn't sure what needed to be returned from where.  Alternatively I could skip the promise and just exit, but then the output would have to be managed in two places.  
All that is to say - let me know if you want me to do this another way.
> Added an option to --skip-cleanup

- lib/utils/config.js
Given this change, we will automatically test (when no user specified config was provided) against release/beta/canary *AND* whatever version is manually specified in the `bower.json` of the consuming app/addon.
This provides the ability to have an app automatically tested against the next upcoming release in each channel, AND against the specific version that it is being developed against.
> Change default scenarios to use Ember's channels.

- lib/utils/bower-helpers.js
Allows ember-try to be used on a CI server like Travis.
See related ember-cli issue here: https://github.com/ember-cli/ember-cli/issues/4222
> Disable bower install interactivity

- lib/utils/scenario-manager.js
- test/scenario-manager-test.js
This commit adds support for overriding bower packages specified in `devDependencies`.
I should add (a) test(s).
> Add support for dev dependencies

- package.json
By default, `npm run-script` includes all `node_modules/.bin/` in `$PATH`, so specifying `node_modules/.bin/` again isn't needed (and will actually not always work on Windows).
> Simplify npm scripts.

- README.md
- lib/commands/testall.js
- lib/commands/try.js
- lib/utils/config.js
- test/commands/testall-test.js
- test/commands/try-test.js
- test/utils/config-test.js
This allows groups of configurations to be used with various commands.
For example, it would be nice in ember-test-helpers to group "legacy" Ember versions together and run them as a single matrix build with:
```
ember try:testall --config-path=config/legacy-scenarios.js
```
Then we could run current scenarios in another matrix build like:
```
ember try:testall --config-path=config/current-scenarios.js
```
> Allow --config-path to be specified to ember-try commands.

- README.md
- lib/tasks/try-each.js
- test/tasks/try-each-test.js
In some circumstances, you may want to know the scenario currently being ran (i.e. one example is generating test results files for each scenario).  This exposes the current scenario name as `EMBER_TRY_CURRENT_SCENARIO` just before running the command and resets it just before cleaning up.
My personal use case for this is to generate a testem report file for each scenario, and to do that I need to be able to detect the scenario in my projects Testem config...
See https://github.com/rwjblue/ember-collection/commit/58c88088ed8abf511f88208932c965f553c0f9c0 for an example of how I tried to work around this (and failed)...
> Expose environment variable for currently running scenario.

- test/bower-adapter-test.js
- test/fixtures/package.json
- test/npm-adapter-test.js
- test/utils/config-test.js
- Some JSCS fixes
- Use ember-feature-flags instead of ember-data as sample dep to not see
warnings
> Quiet npm warnings by appeasing it with changes to the fixture package.json

- all-commands.sh
- lib/utils/run-command.js
- lib/utils/run.js
- package.json
- test/fixtures/dummy-ember-try-config.js
- test/tasks/try-each-test.js
- test/utils/run-command-test.js
Example of what will now work again: `ember try default help --json true`
- Add a script to run various permutations of supported commands, use it
in CI. (This uncovered a few other commands that are not working,
but it seems like they never did. Will open other issues or address.)
> Fix bug: options were not being passed to the command run by `try`

- README.md
- all-commands.sh
- lib/commands/index.js
- lib/commands/testall.js
- lib/commands/try-each.js
- lib/commands/try.js
- lib/tasks/try-each.js
- lib/utils/result-summary.js
- lib/utils/run-command.js
- test/commands/try-each-test.js
- test/commands/try-test.js
- test/helpers/generate-mock-run.js
- test/tasks/try-each-test.js
- test/utils/run-command-test.js
Commands can now be specified in configuration, both top-level and under each scenario. 
New command `ember try:each` that is an exact replacement for `ember try:testall`, with a new name that better fits the ability to configure commands. `ember try:testall` still works. 
Documentation commit coming soon.
> Make commands configurable and add `try:each` command, soft-deprecating `testall`

- README.md
- lib/utils/bower-adapter.js
- lib/utils/dependency-manager-adapter-factory.js
- lib/utils/npm-adapter.js
- test/bower-adapter-test.js
- test/helpers/generate-mock-run.js
- test/npm-adapter-test.js
- Each are passed to their respective package manager's commands that
are run by `ember-try`
- Both are arrays of options as strings, example: `bowerOptions:
['--allow-root']`
> Add 'bowerOptions' and 'npmOptions' as top level configuration options

- README.md
- all-commands.sh
- lib/commands/index.js
- lib/commands/try-one.js
- test/commands/try-one-test.js
- test/commands/try-test.js
- Replaces `ember try <scenario`
- Allows commands other than `ember <something>`
- Allows more robust handling of options passed to the command and to
ember-try
> Add `ember try:one <scenario> (...options) --- <command>`

- README.md
- lib/tasks/try-each.js
- lib/utils/result-summary.js
- test/tasks/try-each-test.js
- If set, the scenario will not fail the overall `ember try` command that was run
Fixes #4
> New configuration option `allowedToFail` per scenario.

- lib/commands/try.js
Prior to this change the message looked like:
```
DEPRECATION: tryCmd command is deprecated in favor of `ember try:one`.
```
Making `tryCmd`  be `ember try` (as is done here) emits the following:
```
DEPRECATION: The `ember try` command is deprecated in favor of `ember try:one`.
```
> Fix deprecation message for `ember try` command.

- lib/tasks/try-each.js
- lib/utils/config.js
Before:
```
% ember v
...snip...
4.95 real         1.18 user         0.18 sys
```
After:
```
% ember v
...snip...
2.09 real         1.34 user         0.27 sys
```
Fixes #74
> Move costly requires to be lazy.

- package.json
"latest" as a version is a source of problems when using along with shrinkwrap, and since now ember-try is part of ember-cli, this is transitively making ember-cli a true pain to use.
> Don't use "latest" as strategy in package.json

- index.js
- package.json
I have an old project running `ember-cli@2.5.x` that I haven't had a chance to update yet (soon!), and I was getting deprecation warnings about ember-try being included in ember-cli, but it seems that didn't happen until `ember-cli@2.6.0`. I've added a condition checking the ember-cli version around the deprecation message.
Fixes #83.
> Skipping deprecation warning if ember-cli is below 2.6

- lib/dependency-manager-adapters/npm.js
- test/dependency-manager-adapters/npm-adapter-test.js
Useful for testing future versions, while not officially supporting them yet.
> add support for npm peerDependencies

- .travis.yml
- README.md
- lib/dependency-manager-adapters/bower.js
- lib/dependency-manager-adapters/npm.js
- lib/utils/result-summary.js
- test/dependency-manager-adapters/bower-adapter-test.js
- test/dependency-manager-adapters/npm-adapter-test.js
- test/fixtures/bower.json
- test/tasks/try-each-test.js
- testem.js
Counterpart to #106 for bower.
As discussed, changed from 'undefined' to 'null' to signify a package should be removed in a scenario.
> Allow removing packages from bower config

- .npmignore
- .travis.yml
- README.md
- all-commands.sh
- fail-if-no-foo.sh
- lib/utils/run.js
- Add note to readme about needing to npm link ember-try
Allows:
`ember try:one <scenario> --- FOO=5 ember test`
`ember try:one <scenario> --- 'ember test && echo 2'` (note quotes)
The same goes for the command in the config file. 
Fixes #94 and #87
> Allow chained commands and setting env vars in commands

- lib/dependency-manager-adapters/bower.js
- test/dependency-manager-adapters/bower-adapter-test.js
Installs bower if its not around, on the first scenario that requires bower
Makes ember-try compatible with ember-cli after https://github.com/ember-cli/ember-cli/pull/6631
h/t @rwjblue
> Install bower if not installed and required by scenarios

- lib/tasks/try-each.js
- test/tasks/try-each-test.js
Works around an upstream issue in ember-cli 2.13 canary versions, and is quite a bit easier to test.
Also tweaked SIGINT handling to queue up a cancel and avoid additional work. This is because in ember-cli 2.9+ we use `capture-exit` so that `process.exit()` does not immediately schedule an exit any longer (so the semantics that we intended with the prior SIGINT logic were generally broken already).
Addresses the issue identified in https://github.com/ember-cli/ember-cli/issues/6779.
> Leverage command return value instead of process.exit.

- lib/dependency-manager-adapters/bower.js
- test/dependency-manager-adapters/bower-adapter-test.js
- test/tasks/try-each-test.js
> Support having bower scenarios without having a bower.json initially

- all-commands.sh
Remove `node_modules/ember-try` on each travis.ci run to avoid accumulation of nested folders because of caching of `node_modules` folder and repeated `npm link` / `npm link ember-try` commands being executed on each `client-test` travis scenario run.
Accumulation example can be observed here: https://travis-ci.org/ember-cli/ember-try/jobs/206107877
> fix CI client-test cache problem

- lib/dependency-manager-adapters/npm.js
- test/dependency-manager-adapters/npm-adapter-test.js
- test/utils/dependency-manager-adapter-factory-test.js
- use `yarn` package manager instead of npm if `yarn.lock` is present or `yarn --version` command returns anything other than error.
- if `yarn.lock` is present on the project it gets backed up / restored / cleaned up.
> Minimal yarn support

- .npmignore
- .travis.yml
- lib/dependency-manager-adapters/npm.js
- lib/tasks/try-each.js
- package.json
- smoke-test.sh
- test/dependency-manager-adapters/npm-adapter-test.js
- test/fixtures/dummy-ember-try-config-with-npm-scenarios.js
- Also remove unnecessary install step
Managed to expose the bug with `smoke-test.sh` but cannot get it to pass because CI is using the ember-try included with ember-cli, rather than the one in the repo. This problem was not exposed with `all-commands.sh` because it did not include any npm scenarios.
Fixes #121
> Require ResultSummary before any npm scenarios run

- package.json
It is not used anymore and has a security issue:
https://nodesecurity.io/advisories/310
> Remove sync-exec as it is not used anymore

- README.md
- lib/dependency-manager-adapters/npm.js
- lib/utils/dependency-manager-adapter-factory.js
- lib/utils/scenario-manager.js
- test/dependency-manager-adapters/npm-adapter-test.js
- test/fixtures/dummy-ember-try-config-with-npm-scenarios.js
- test/tasks/try-each-test.js
This is a naïve fix for #133. It would seemingly work to merge, but I’m not sure if more nuance is needed, or whether the change should extend further.
1. I made use of `throw` because it was the minimal change, since that’s what `execFileSync` would do when `yarn --version` failed. I could instead strip out the exception handling and directly use the simple boolean check of `isFile()`.
2. The existing test for this doesn’t really exercise things fully, it mocks `_runYarnCheck`. Would it be worth using a true `yarn.lock` for testing?
3. What happens if a `yarn.lock` is detected but `yarn` itself isn’t present? Should the `execFileSync` perhaps remain? 🤔
Let me know your thoughts and I’m happy to improve this. Thanks for `ember-try`, it’s endlessly useful!
> Change Yarn detection to look for lockfile

- lib/dependency-manager-adapters/npm.js
- test/dependency-manager-adapters/npm-adapter-test.js
Avoid using package-lock.json and shrinkwrap files per https://docs.npmjs.com/cli/install (and experimentation)
Fixes #144
> Use --no-shrinkwrap option to npm

- lib/dependency-manager-adapters/bower.js
- lib/utils/run-command.js
to prevent them from looking like separate arguments when run with the shell
fixes #149
> Put quotes around paths 

- appveyor.yml
- package.json
- test/utils/config-test.js
https://github.com/ember-cli/ember-try-config/pull/15 changed behaviour in 2.2.0 to set ember-source to null.
This is desired behaviour but required tweaking some tests.
> Bump ember-try-config

- all-commands.sh
- lib/dependency-manager-adapters/bower.js
- lib/utils/config.js
- lib/utils/run.js
- test/dependency-manager-adapters/bower-adapter-test.js
- test/tasks/try-each-test.js
- test/utils/config-test.js
- test/utils/dependency-manager-adapter-factory-test.js
- test/utils/scenario-manager-test.js
For scenarios that
1. do not already have a dependency or dev dependency on bower and
2. have bower dependencies
Also assert that
1. npm is ran before bower
2. if bower is run, a local bower is found
This PR is a continuation of, and supersedes, #151.
Fixes #141 
Fixes #150
> Implicitly add an npm dev dependency on bower

- lib/dependency-manager-adapters/bower.js
- lib/utils/dependency-manager-adapter-factory.js
- package.json
- test/dependency-manager-adapters/bower-adapter-test.js
- test/tasks/try-each-test.js
- test/utils/dependency-manager-adapter-factory-test.js
>  Ensure `bower` is not required when no bower dependencies are present.

- README.md
- package.json
- test/utils/config-test.js
- yarn.lock
This is a breaking change: only projects starting with ember provided by
npm will work with versionCompatibility, going forward.
> Upgrade ember-try-config to 3.0

- test/dependency-manager-adapters/bower-adapter-test.js
- test/dependency-manager-adapters/npm-adapter-test.js
- test/tasks/try-each-test.js
This ensures:
* tests fail with the rejection reason
* assertions in previous promise steps who fail, are surfaced as the origin of the test failure
> Let mocha handle rejected promises.

- package.json
- yarn.lock
This PR updates the `cli-table2` dependency to `cli-table3`, which fixes one of the `npm audit` warnings :)
`cli-table2` (like `cli-table` itself) is no longer maintained. In jamestalmage/cli-table2#43 a couple of people have offered to take over maintenance but the current maintainer did not respond so as a result the project was forked to https://github.com/cli-table/cli-table3.
> Update `cli-table2` to `cli-table3`

- README.md
- lib/dependency-manager-adapters/npm.js
- lib/dependency-manager-adapters/workspace.js
- lib/tasks/try-each.js
- lib/utils/dependency-manager-adapter-factory.js
- package.json
- test/dependency-manager-adapters/workspace-adapter-test.js
- test/fixtures/package-with-workspaces.json
- test/utils/dependency-manager-adapter-factory-test.js
- yarn.lock
This PR adds support for workspaces to allow ember-try to run scenarios in monorepo based repositories quickly and efficiently. Workspaces are currently only supported by Yarn, but NPM has indicated that they [want to add support in the future](https://blog.npmjs.org/post/173239798780/beyond-npm6-the-future-of-the-npm-cli), and other tools for managing monorepos such as Lerna integrate nicely with workspaces, so it feels like the best way to add this type of support.
To enable workspaces, users need to install `ember-cli` and `ember-try` in the top level monorepo package, add a `config/ember-try.js` file, and set `useWorkspaces` and `useYarn` to true in that config. This means that the adapter is limited to using one try config for _all_ of the packages in the repo. For most monorepo use …
> [feat] Adds support for Yarn/NPM workspaces

- README.md
We should add the `useYarn` into the example ember-try configuration file. This PR also copies @backspace's documentation into a comment above it. Ping #168
> Copy `useYarn` into example configuration file

- README.md
see [#234](https://github.com/ember-cli/ember-try/issues/234)
> update example bower-supplied ember scenario example

- lib/dependency-manager-adapters/npm.js
Since this message is shown when you run `yarn test` it is not obvious which file you're supposed to add this to. Especially if you don't know ember-try.
Now it should be easier for newcomers.
> Clarify useYarn option

- appveyor.yml
It keeps timing out. This balances keeping some windows smoke-testing
against being able to to develop at all.
I will continue investigating alternatives, but so far none have worked out (Travis Windows, Azure Pipelines).
> Vastly reduce appveyor testing. Keep it to one smoke-test only.

- lib/dependency-manager-adapters/npm.js
- test/dependency-manager-adapters/npm-adapter-test.js
- test/dependency-manager-adapters/workspace-adapter-test.js
This PR adds resolution support for ember-try configs that are using yarn.
It uses the same merging strategy that the dependencies, devDependencies, and
peerDependencies use.
> Add yarn resolutions

- CHANGELOG.md
PRing CHANGELOG to check that going to v1.2.0 makes sense
> Update a CHANGELOG for v1.2.0

- README.md
Example for https://github.com/ember-cli/ember-try/pull/259
> Include resolutions example in README

- .travis.yml
- lib/dependency-manager-adapters/npm.js
- package.json
- run-smoke-test.sh
- smoke-test-app/package-lock.json
- smoke-test-app/package.json
- smoke-test-app/smoke-test-yarn.sh
- smoke-test-app/yarn.lock
- test/dependency-manager-adapters/npm-adapter-test.js
- test/fixtures/dummy-ember-try-config-with-yarn-scenarios.js
Fixes #167 
Closes #280 
This is an attempt to achieve the same as https://github.com/ember-cli/ember-try/pull/280 but without breaking backwards compatibility for node@4
I have been successful in making it only run npm prune with npm@4 and have also added tests that cover that issue. You will see some changes to the build scripts and this is because of slightly different behaviour between npm and yarn when it comes to installing packed `.tgz` files (which the smoke tests rely on)
> Fixing npm@5 and npm@6 - without breaking backwards compatibility

- README.md
- lib/dependency-manager-adapters/npm.js
- lib/dependency-manager-adapters/workspace.js
- lib/utils/dependency-manager-adapter-factory.js
- test/dependency-manager-adapters/npm-adapter-test.js
- test/dependency-manager-adapters/workspace-adapter-test.js
Currently, ember-try is running yarn with the --no-lockfile option, which will install packages whose version may differ from the actual current yarn.lock file in the project. To get a true dependency environment during testing, this PR aims to add support for using the project's yarn.lock file when using ember-try by adding a config flag called useYarnLockFile that users can pass in to determine whether to use the project's yarn.lock file.
> Add support for using yarn.lock file

- package.json
- yarn.lock
Reverts ember-cli/ember-try#419
eslint-plugin-ember@7 requires Node 8+, but we are still supporting Node 6.
> Revert "Bump eslint-plugin-ember from 6.4.1 to 7.5.0"

- lib/dependency-manager-adapters/npm.js
- lib/dependency-manager-adapters/workspace.js
- test/dependency-manager-adapters/workspace-adapter-test.js
Yarn workspaces can have two [different definitions](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/)
```
"workspaces": [
"packages/*"
]
```
and
```
"workspaces": {
"packages": ["packages/*"],
"nohoist": ["**/react-native", "**/react-native/**"]
}
```
This PR adds support for the second definition
> Handle additional `yarn` workspace definition formats

- lib/dependency-manager-adapters/workspace.js
- test/dependency-manager-adapters/workspace-adapter-test.js
- test/utils/dependency-manager-adapter-factory-test.js
Fundamentally, `Adapter.prototype.cleanup` **cannot** require `Adatper.prototype.setup` to have been called. _Most_ of the time `.setup` is called before `.cleanup` (this happens with `ember try:each` and `ember try:one`), but when `--skip-cleanup` is specified (e.g.  `ember try:one scenario-name --skip-cleanup`) and you subsequently run `ember try:reset` the `.setup` happened in a completely different process.
The issue here is a misunderstanding when we added the `WorkspaceAdapter` initially. Basically, the assumtion was that `.setup` was for setting up both local instance state (e.g. the `this._packageAdapters` array) **and** for actually preparing for a `ember try:...` run (doing backups / etc).
The fix is to move the internal state setup code directly into `init`/`constructor, and …
> Ensure Yarn Workspace adapter supports `ember try:reset`.

- .github/workflows/ci.yml
- appveyor.yml
- package.json
which should match our support matrix to all of the currently officially supported Node.js versions.
> Drop support for Node.js 6.x, 8.x, 11.x and 13.x

- index.js
- lib/commands/config.js
- lib/commands/try-each.js
- lib/commands/try-ember.js
- lib/utils/config.js
- test/utils/config-test.js
This makes `ember-try` work much closer to how other ecosystem tools work (`@ember/optional-features`, `ember-cli`'s lookup of `config/environment.js` and `config/targets.js`, `ember-cli-code-coverage`).
This is not a breaking change, as it still falls back to using the older hardcoded `config/ember-try.js` path.
Fixes https://github.com/ember-cli/ember-try/issues/305
> Use `ember-addon.configPath` from `package.json` if defined.

- .github/workflows/ci.yml
This will reduce the overall number of scenarios that we run through for
that one smoke test job.
> Limit SemVer range smoke test to > 2.16 < 3.0.0.

- lib/utils/scenario-manager.js
- test/tasks/try-each-test.js
- test/utils/scenario-manager-test.js
> Remove requirement to have dependency managers.

- .github/workflows/ci.yml
Scheduled jobs are automatically disabled after a certain amount of days, thanks to the cryptocurrency community.
This commit removes the schedule to keep the job enabled for PRs and regular commits
/cc @kategengler
> CI: Remove job schedule

- lib/dependency-manager-adapters/pnpm.js
- lib/utils/dependency-manager-adapter-factory.js
- test/dependency-manager-adapters/pnpm-adapter-test.js
As discussed via Discord I've created a new dependency manager adapter for `pnpm`, largely based on the existing `npm` adapter.
The main differences to the `npm` adapter are:
- We do not backup the `node_modules` folder and instead run `pnpm install` once more in the cleanup phase
- We do not use `--no-lockfile` so that we only have to resolve the dependencies that have actually changed, resulting in a much smaller amount of necessary dependency downloads
I've implemented a `usePnpm` option, similar to the existing `useYarn` option. I'm aware that this might not be ideal, but it works well enough for now and can still be refactored later.
Resolves #744
> Implement `pnpm` adapter

- test/dependency-manager-adapters/npm-adapter-test.js
This should make the test code a little easier on the eyes :)
> tests/npm-adapter: Use async/await instead of promise chains

- .github/workflows/ci.yml
- package.json
See [Node Releases](https://github.com/nodejs/release#release-schedule)
Floating deps test is currently failing with things like
> The engine "node" is incompatible with this module. Expected version "^12.13.0 || ^14.15.0 || >=16.0.0". Got "10.24.1"
Which is to be expected for out-of-support node versions.
> Bump node to supported versions

- .github/dependabot.yml
- .github/workflows/ci.yml
- package.json
- test/fixtures/dummy-ember-try-config-fs-extra-scenarios.js
- yarn.lock
fs-extra brought in a breaking change here:
https://github.com/jprichardson/node-fs-extra/pull/582
where it breaks ember-try when copying node_modules/ and there's a symlink in it. The bug would either prevent ember-try from running or cleaning up after try-each.
Testing done:
`yarn test` passed locally.
@Co-authored-by hjdivad
> Downgraded fs-extra version to 6.x to fix a fs.copy related issue.

- README.md
- lib/dependency-manager-adapters/npm.js
- test/dependency-manager-adapters/npm-adapter-test.js
This PR is supposed to help with the issue that is described in https://github.com/emberjs/ember-render-modifiers/issues/64
Essentially npm thinks that ranges shouldn't be satisfied if you are using pre-releases. You can overcome this if you use an `overrides` in npm which works in a very similar way to yarn resolutions. 
The issue is that if you provide an `overrides` config to ember-try it will just ignore it: 
```
{
name: 'ember-release',
npm: {
devDependencies: {
'ember-source': await getChannelURL('release'),
},
overrides: {
'ember-source': '$ember-source',
},
},
},
```
This PR implements npm overrides in much the same way as yarn resolutions 👍  in fact I copy and pasted all of the resolutions tests and just changed resolutions to overrides in most cases 😂
> Add support for npm overrides

- lib/utils/dependency-manager-adapter-factory.js
RFC: https://github.com/emberjs/rfcs/pull/907
Implementation PR: https://github.com/ember-cli/ember-cli/pull/10287
Advancement PR: https://github.com/emberjs/rfcs/pull/932
- https://github.com/NullVoxPopuli/pnpm-default-addon-demo-ember-try-remove-pnpm-warning/actions/runs/5359698497
In this _more involved_ CI setup, having the default pnpm flags  https://github.com/NullVoxPopuli/ember-data-resources/actions/runs/5365368548/jobs/9734152943 and it also works
> Remove warning about pnpm

- README.md
RFC: https://github.com/emberjs/rfcs/pull/907
Implementation PR: https://github.com/ember-cli/ember-cli/pull/10287
Advancement PR: https://github.com/emberjs/rfcs/pull/932
> Document pnpm options and behavior

- .github/workflows/ci.yml
This just takes some inspiration from the default output of a new Ember addon 👍
> Update github CI yaml

- README.md
- lib/dependency-manager-adapters/pnpm.js
- test/dependency-manager-adapters/pnpm-adapter-test.js
Previous try-hard attempt here: https://github.com/ember-cli/ember-try/pull/958/files
(lesson for me, don't trust any web site ever, always check `--help`)
> Use pnpm's --no-lockfile

- .github/workflows/ci.yml
- .github/workflows/release.yml
- lib/dependency-manager-adapters/npm.js
- package.json
- smoke-test-app/package-lock.json
- smoke-test-app/package.json
- smoke-test-app/tests/dummy/config/ember-try.js
- smoke-test-app/yarn.lock
- test/dependency-manager-adapters/npm-adapter-test.js
- yarn.lock
> Drop Node.js 14 support

- .eslintignore
- .gitignore
- .npmignore
- lib/dependency-manager-adapters/npm.js
- smoke-test-app/.eslintignore
- smoke-test-app/.gitignore
- smoke-test-app/.npmignore
- smoke-test-app/.prettierignore
- test/dependency-manager-adapters/npm-adapter-test.js
- test/dependency-manager-adapters/pnpm-adapter-test.js
- test/dependency-manager-adapters/workspace-adapter-test.js
Closes https://github.com/ember-cli/ember-try/issues/189.
Closes https://github.com/ember-cli/ember-try/issues/598.
Closes https://github.com/ember-cli/ember-try/issues/813.
> Stop backing up the `node_modules` folder

- README.md
- lib/dependency-manager-adapters/npm.js
- smoke-test-app/.eslintignore
- smoke-test-app/.gitignore
- smoke-test-app/.npmignore
- smoke-test-app/.prettierignore
- test/dependency-manager-adapters/npm-adapter-test.js
- test/dependency-manager-adapters/workspace-adapter-test.js
Closes https://github.com/ember-cli/ember-try/pull/961.
> Drop support for npm v4

- .eslintignore
- .gitignore
- .npmignore
- README.md
- lib/dependency-manager-adapters/npm.js
- lib/dependency-manager-adapters/pnpm.js
- lib/utils/backup.js
- package.json
- smoke-test-app/.eslintignore
- smoke-test-app/.gitignore
- smoke-test-app/.npmignore
- smoke-test-app/.prettierignore
- test/dependency-manager-adapters/npm-adapter-test.js
- test/dependency-manager-adapters/pnpm-adapter-test.js
- test/dependency-manager-adapters/workspace-adapter-test.js
- test/tasks/reset-test.js
- yarn.lock
Builds on #964, so should be reviewed and merged first.
Closes https://github.com/ember-cli/ember-try/issues/599.
> Use the system's temp folder for backing up package-manager files

- README.md
- lib/dependency-manager-adapters/pnpm.js
- lib/utils/backup.js
- package.json
- test/dependency-manager-adapters/pnpm-adapter-test.js
- yarn.lock
pnpm versions 8.0.0 to 8.6.* had the `resolution-mode` setting inverted which caused troubles with unexpected versions of dependencies pulled for `ember-try` tests.
This is an attempt to fix those issues by enfrocing `resolution-mode=highest` via project-local `.npmrc`.
> ember-try: Enforce resolution-mode=highest for pnpm versions 8.0.0 to 8.6.*

- lib/dependency-manager-adapters/pnpm.js
- test/dependency-manager-adapters/pnpm-adapter-test.js
Closes: https://github.com/ember-cli/ember-try/issues/993
> pnpm: Ignore scripts by default

- .eslintignore
- .gitignore
- .npmignore
- lib/utils/dependency-manager-adapter-factory.js
- smoke-test-app/.eslintignore
- smoke-test-app/.gitignore
- smoke-test-app/.npmignore
- smoke-test-app/.prettierignore
- test/utils/dependency-manager-adapter-factory-test.js
> Clean up everything related to Bower

- lib/commands/reset.js
- lib/tasks/reset.js
- lib/tasks/try-each.js
- lib/utils/result-summary.js
- lib/utils/scenario-manager.js
- test/tasks/try-each-test.js
> Remove use of `core-object` for utils

- README.md
It came up on Discord that seeing `ember-1.11` in usage examples is confusing: https://discord.com/channels/480462759797063690/491905849405472769/923319343088017518
> Use scenario names available in default `addon` blueprint

- .eslintrc.js
- test/.eslintrc.js
ESLint v9 doesn't support this anymore (I think).
> Use only one ESLint config file

- README.md
- lib/dependency-manager-adapters/npm.js
- lib/dependency-manager-adapters/workspace.js
- lib/utils/config.js
- lib/utils/dependency-manager-adapter-factory.js
- test/dependency-manager-adapters/workspace-adapter-test.js
- test/fixtures/dummy-ember-try-config-with-yarn-scenarios.js
- test/tasks/try-each-test.js
- test/utils/config-test.js
- test/utils/dependency-manager-adapter-factory-test.js
So we have just one option to determine the desired package manager, instead of two (`usePnpm` and `useYarn`).
It's also a bit unclear what happens if you use both of them, or set them to `false`.
This also simplifies [this bit](https://github.com/ember-cli/ember-cli/blob/master/blueprints/addon/files/addon-config/ember-try.js#L8-L9) in the blueprints, as we can write `packageManager: '<%= packageManager %>'` instead.
> Support a `packageManager` option (instead of `usePnpm` and `useYarn`)

- .codeclimate.yml
- .eslintrc.js
- .github/dependabot.yml
- .github/workflows/ci.yml
- .gitignore
- .prettierignore
- README.md
- RELEASE.md
- package.json
- smoke-test-app/README.md
- smoke-test-app/tests/dummy/app/index.html
- smoke-test-app/tests/dummy/config/ember-cli-update.json
- smoke-test-app/tests/dummy/config/ember-try.js
- smoke-test-app/tests/index.html
- test/fixtures/package-with-workspaces.json
- test/fixtures/package.json
- yarn.lock
- Simplifies the ESLint config, since this is a Node-only package
- Runs Prettier separately
Easiest to review commit per commit, and skipping the second commit (format changes).
> Update lint setup

- lib/utils/run.js
- package.json
- test/helpers/generate-mock-run.js
- test/tasks/try-each-test.js
- test/utils/run-command-test.js
- yarn.lock
The `mockery` project is old, and archived.
I also had some issues with it when converting the test suite to ES modules, so seemed easiest to just get rid of it, and use a more "vanilla" approach.
> Remove use of `mockery`

- lib/commands/config.js
- lib/commands/try-each.js
- lib/commands/try-ember.js
- lib/commands/try-one.js
- lib/dependency-manager-adapters/base.js
- lib/dependency-manager-adapters/pnpm.js
- lib/dependency-manager-adapters/workspace.js
- lib/tasks/try-each.js
- lib/utils/config.js
- lib/utils/console.js
- lib/utils/result-summary.js
- lib/utils/scenario-manager.js
- test/tasks/try-each-test.js
Part of decoupling `ember-try` from `ember-cli`.
> Remove use of ember-cli `ui` instance

- .github/workflows/plan-release.yml
- .github/workflows/publish.yml
The rare thing happened! two PRs that affected each other were merged without rebasing 🫠 https://github.com/ember-cli/ember-try/pull/1049 means that https://github.com/ember-cli/ember-try/pull/1039 should not have specified pnpm versions in the github jobs
No big deal, this PR fixes that 🎉
> use package.json pnpm version for release-plan

- package.json
> Use `pnpm` for running scripts

- lib/utils/config.js
- test/utils/config-test.js
I suspect (almost) no users will be affected by this.
If someone does run into this, feel free to give me a ping,
and I will try to suggest a proper migration path.
> Remove passing an ember-cli `project` instance to the config function

- lib/commands/config.js
- lib/commands/reset.js
- lib/commands/try-each.js
- lib/commands/try-ember.js
- lib/commands/try-one.js
- lib/tasks/reset.js
- lib/tasks/try-each.js
- lib/utils/config.js
- lib/utils/dependency-manager-adapter-factory.js
- test/commands/try-each-test.js
- test/commands/try-ember-test.js
- test/commands/try-one-test.js
- test/tasks/reset-test.js
- test/tasks/try-each-test.js
- test/utils/config-test.js
Part of decoupling `ember-try` from `ember-cli`.
This way, only the code in `lib/commands` is coupled to `ember-cli`.
The next step would be to move the `run` portion of the commands to separate files.
This would allow us to move everything to ES modules, except the commands.
The commands can async import and run the ES modules.
> Don't use ember-cli `project` instance outside of ember-cli commands

- .github/workflows/plan-release.yml
- .github/workflows/publish.yml
- package.json
- pnpm-lock.yaml
Used kategengler/create-release-plan#kg-reusable-actions (PR'd to create-release-plan)
> Update release-plan workflows.
